name: CI/CD with Ngrok

on:
  push:
    branches:
      - main

jobs:
  build-test-expose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory
        run: ls -l target/

      - name: Install Ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz | tar xz
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Run Spring Boot App
        run: |
          java -jar target/ar-guideline-0.0.1-SNAPSHOT.jar &  # Start Spring Boot app
          sleep 10  # Allow time for the app to start

      - name: Expose Port with Ngrok
        run: |
          # Start Ngrok to expose the app
          ngrok http 8086 > /dev/null &

          # Wait for Ngrok to start and the API to become available
          until curl -s localhost:4040/api/tunnels; do
            echo "Waiting for Ngrok to start..."
            sleep 2
          done

          # Fetch the Ngrok public URL from the API response
          NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')

          # Display the URL
          echo "Public URL: $NGROK_URL"
