name: CI/CD with Ngrok

on:
  push:
    branches:
      - main

jobs:
  build-test-expose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Install Ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz | tar xz
          sudo mv ngrok /usr/local/bin/

      - name: Authenticate Ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Run Spring Boot App
        run: java -jar target/*.jar &
        working-directory: ./target

      - name: Expose Port with Ngrok
        run: |
          ngrok http 8086 > /dev/null &
          sleep 5
          NGROK_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Public URL: $NGROK_URL"
