name: CI/CD with Ngrok

on:
  push:
    branches:
      - main  # Runs only on the 'main' branch

jobs:
  build-test-expose:
    runs-on: windows-latest  # Change to windows-latest for Windows environment

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Authenticate Ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Run Spring Boot App
      run: |
        Start-Process -NoNewWindow -FilePath java -ArgumentList "-jar target\*.jar" -WorkingDirectory .\target

    - name: Expose Spring Boot App via Ngrok
      run: |
        Start-Process -NoNewWindow -FilePath ngrok -ArgumentList "http", "8086"
        Start-Sleep -Seconds 5  # Wait for Ngrok to initialize
        $NGROK_URL = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels | Select-Object -ExpandProperty tunnels | Select-Object -First 1 | Select-Object -ExpandProperty public_url
        Write-Host "Ngrok Public URL: $NGROK_URL"
        echo "NGROK_PUBLIC_URL=$NGROK_URL" >> $GITHUB_ENV

    - name: Output Ngrok Public URL